### ISSUE TITLE
Using chekr with Azure Kubernetes Service

### ISSUE THREAD

**Issue by tiwood** [ckotzbauer/chekr#88]
I'm trying to use chekr with AKS Clusters which results in the following error message:

`FATA[0000] Could not create Kubernetes client from config!  error="no Auth Provider found for name \"azure\""`

Is there a way to get this to work with the current version?

This is the `user` configuration generated by azurecli:

```yaml
users:
- name: a-user
  user:
    auth-provider:
      config:
        apiserver-id: 00000000-0000-0000-0000-000000000000
        client-id: 00000000-0000-0000-0000-000000000000
        config-mode: "1"
        environment: AzurePublicCloud
        tenant-id: 00000000-0000-0000-0000-000000000000
      name: azure
```
